### PR TITLE
new relase for vc-6

### PR DESCRIPTION
**Pull request by dmatetelki**

### CODE REVIEW

**Comment by Dridi** [comment]
If you wish to compile against both 4.1 and trunk, here is a workaround:

https://github.com/Dridi/libvmod-querystring/blob/9f4a3564fe8d1845b07b6d3741ed5c48443f4d6e/src/vmod_querystring.c#L26-L36

**Comment by Dridi** [comment]
@dmatetelki, @hermunn, any progress on applying the workaround as described in varnish-modules?

**Comment by hermunn** [comment]
@dmatetelki is working on it. I can help, but I am not back until Thursday morning.

**Comment by dmatetelki** [comment]
@Dridi : great success! 4.1-plus is done, master-plus has 1 crashing test, minimal changes between the the 2 branches

**Pull request closed without merging**
