### PR TITLE
improve compilation instructions

### PR DESCRIPTION
**Pull request by dbu**
i struggled quite a bit to figure out how to build this module. the readme could explain a bit more.

would this vmod also be available in a .deb file like the simple varnish-modules?

### CODE REVIEW

**Comment by dbu** [comment]
do you want me to change something or is this fine to be merged? i think it would be useful for others...

**Comment by Dridi** [comment]
Hi @dbu,

Apologies for the late response but after reviewing your proposed change I would indeed like to change a few things.

The main thing is that if you grab a release archive, you shouldn't need any build dependency related to autotools:

https://download.varnish-software.com/libvmod-curl/

You only need them when building from git, when working on the module itself.

Instead, I would rather keep the installation instructions mostly as-is and add development instructions.

Please note how it is done for varnish-modules:

https://github.com/varnish/varnish-modules/#installation
https://github.com/varnish/varnish-modules/#development

Obviously, we weren't as comprehensive as you regarding development dependencies :)

**Comment by dbu** [comment]
thanks for the pointers. i adjusted the readme to separate between the source distribution installation and development, and aligned it with the varnish-modules repository. however, i think the automake and other dev dependencies are required even when using the source distribution. its only autotools-dev that is for bootstrap only.

**Comment by Dridi** [comment]
Plain make should be enough, automake is really only needed for development.

See this module RPM spec:

https://github.com/Dridi/libvmod-querystring/blob/master/vmod-querystring.spec.in#L11-L15

It doesn't "BuildRequires" automake, and now I'm realizing we need pkgconfig and python too :)

**Comment by dbu** [comment]
so `./configure` would not be needed? maybe its easier if you pick this up from here and wrap it up. otherwise i will keep guessing what you mean. i am by no means an expert in compiling stuff, i usually work on PHP :-D

**Comment by Dridi** [comment]
The `./configure` script is part of the release archive, and the role of autoconf, automake and libtool is ultimately to generate the configure script for downstream distribution.

**Comment by dbu** [comment]
updated the readme.

**Comment by Dridi** [comment]
Thanks, I will review this when I get the occasion to do it quietly and merge it. If I find other things to adjust, I will do it myself.

Thanks for your help and patience!

**Pull request closed without merging**
