### PR TITLE
Explain how to use the the body() function

### LINKED ISSUE #15: #012 character occurring (instead of) CRLF in response body
Hi,

I download and installed the library as per instructions. When I do a request on curl, the response body (when invoking curl.body(URL)) returns the BODY along with the "#012" character for every occurrence of CRLF. 

I was advised to raise a ticket when I posted about the same in the varnish-cache forum.

### PR DESCRIPTION
**Pull request by aondio**
Fixes #15

### CODE REVIEW

**Comment by Dridi** [comment]
LGTM, what about binary bodies?

**Comment by aondio** [comment]
That is user responsibility to check which kind of response body they expect.

**Comment by fgsch** [comment]
Looks good but that won't be visible in the generated manpage.
Not sure if that was your intention or not.

**Comment by aondio** [comment]
I'm aware that the man page is generated from the README, but I wanted this patch to address this specific issue and nothing else.
My plan was to get this one merged and then write another patch to have the man page generated from the VCC file(as it should be in a VMOD).

**Pull request merged**
